import type { AquaCrudConfig } from '@/features/aqua-core/types/aqua-crud';

export const dailyWeathersConfig: AquaCrudConfig = {
  key: 'dailyWeathers',
  title: 'aqua.pages.dailyWeathers.title',
  description: 'aqua.pages.dailyWeathers.description',
  endpoint: 'DailyWeather',
  listStaleTimeMs: 30000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'weatherDate', label: 'aqua.fields.weatherDate', type: 'date', required: true },
    {
      key: 'weatherTypeId',
      label: 'aqua.fields.weatherTypeId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'WeatherType',
        labelKeys: ['code', 'name'],
        valueKey: 'id',
        staleTimeMs: 120000,
      },
    },
    {
      key: 'weatherSeverityId',
      label: 'aqua.fields.weatherSeverityId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'WeatherSeverity',
        labelKeys: ['code', 'name'],
        valueKey: 'id',
        staleTimeMs: 120000,
      },
    },
    { key: 'temperatureC', label: 'aqua.fields.temperatureC', type: 'number' },
    { key: 'windKnot', label: 'aqua.fields.windKnot', type: 'number' },
    { key: 'waterTemperatureSurfaceC', label: 'aqua.fields.waterTemperatureSurfaceC', type: 'number' },
    { key: 'waterTemperatureDepthC', label: 'aqua.fields.waterTemperatureDepthC', type: 'number' },
    { key: 'dissolvedOxygenMgL', label: 'aqua.fields.dissolvedOxygenMgL', type: 'number' },
    { key: 'salinityPpt', label: 'aqua.fields.salinityPpt', type: 'number' },
    { key: 'ph', label: 'aqua.fields.ph', type: 'number' },
    { key: 'currentSpeedKn', label: 'aqua.fields.currentSpeedKn', type: 'number' },
    { key: 'waveHeightM', label: 'aqua.fields.waveHeightM', type: 'number' },
    { key: 'turbidityNtu', label: 'aqua.fields.turbidityNtu', type: 'number' },
    { key: 'ammoniaMgL', label: 'aqua.fields.ammoniaMgL', type: 'number' },
    { key: 'nitriteMgL', label: 'aqua.fields.nitriteMgL', type: 'number' },
    { key: 'algalBloomIndex', label: 'aqua.fields.algalBloomIndex', type: 'number' },
    { key: 'sensorHealthScore', label: 'aqua.fields.sensorHealthScore', type: 'number' },
    { key: 'sensorRecordedAt', label: 'aqua.fields.sensorRecordedAt', type: 'datetime' },
    { key: 'dataSource', label: 'aqua.fields.dataSource', type: 'text' },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'weatherDate', label: 'aqua.fields.weatherDate' },
    { key: 'weatherTypeName', label: 'aqua.fields.weatherTypeId' },
    { key: 'weatherSeverityName', label: 'aqua.fields.weatherSeverityId' },
    { key: 'weatherSeverityScore', label: 'aqua.fields.weatherSeverityScore' },
    { key: 'operationalRiskScore', label: 'aqua.fields.operationalRiskScore' },
    { key: 'operationalRiskLevel', label: 'aqua.fields.operationalRiskLevel' },
    { key: 'dissolvedOxygenMgL', label: 'aqua.fields.dissolvedOxygenMgL' },
    { key: 'salinityPpt', label: 'aqua.fields.salinityPpt' },
    { key: 'ph', label: 'aqua.fields.ph' },
  ],
};
