import type { AquaCrudConfig } from '@/features/aqua-core/types/aqua-crud';
import { localDateString } from '@/features/quick-daily-entry/utils/quick-operations';

export const transfersConfig: AquaCrudConfig = {
  key: 'transfers',
  title: 'aqua.pages.transfers.title',
  description: 'aqua.pages.transfers.description',
  endpoint: 'Transfer',
  postingSlug: 'transfer',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferNo', label: 'aqua.fields.transferNo', type: 'text', required: true },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'transferNo', label: 'aqua.fields.transferNo' },
    { key: 'transferDate', label: 'aqua.fields.transferDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
  ],
  defaultValues: { status: 0 },
};

export const transferLinesConfig: AquaCrudConfig = {
  key: 'transferLines',
  title: 'aqua.pages.transferLines.title',
  description: 'aqua.pages.transferLines.description',
  endpoint: 'TransferLine',
  createEndpoint: 'TransferLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'transferId',
      label: 'aqua.fields.transferId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'Transfer',
        labelKeys: ['transferNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromProjectCageId',
      label: 'aqua.fields.fromProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'toProjectCageId',
      label: 'aqua.fields.toProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'fromProjectCode', label: 'aqua.fields.projectCode' },
    { key: 'fromCageCode', label: 'aqua.fields.fromCageCode' },
    { key: 'fromCageName', label: 'aqua.fields.cageName' },
    { key: 'toProjectCode', label: 'aqua.fields.projectCode' },
    { key: 'toCageCode', label: 'aqua.fields.toCageCode' },
    { key: 'toCageName', label: 'aqua.fields.cageName' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { transferDate: localDateString() },
};

export const warehouseTransfersConfig: AquaCrudConfig = {
  key: 'warehouseTransfers',
  title: 'aqua.pages.warehouseTransfers.title',
  description: 'aqua.pages.warehouseTransfers.description',
  endpoint: 'WarehouseTransfer',
  postingSlug: 'warehouse-transfer',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferNo', label: 'aqua.fields.transferNo', type: 'text', required: true },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'transferNo', label: 'aqua.fields.transferNo' },
    { key: 'transferDate', label: 'aqua.fields.transferDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
  ],
  defaultValues: { status: 0 },
};

export const warehouseTransferLinesConfig: AquaCrudConfig = {
  key: 'warehouseTransferLines',
  title: 'aqua.pages.warehouseTransferLines.title',
  description: 'aqua.pages.warehouseTransferLines.description',
  endpoint: 'WarehouseTransferLine',
  createEndpoint: 'WarehouseTransferLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'warehouseTransferId',
      label: 'aqua.fields.warehouseTransferId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'WarehouseTransfer',
        labelKeys: ['transferNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromWarehouseId',
      label: 'aqua.fields.fromWarehouseId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Warehouse',
        labelKeys: ['erpWarehouseCode', 'warehouseName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    {
      key: 'toWarehouseId',
      label: 'aqua.fields.toWarehouseId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Warehouse',
        labelKeys: ['erpWarehouseCode', 'warehouseName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'fromWarehouseCode', label: 'aqua.fields.fromWarehouseCode' },
    { key: 'fromWarehouseName', label: 'aqua.fields.fromWarehouseId' },
    { key: 'toWarehouseCode', label: 'aqua.fields.toWarehouseCode' },
    { key: 'toWarehouseName', label: 'aqua.fields.toWarehouseId' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { transferDate: localDateString() },
};

export const cageWarehouseTransfersConfig: AquaCrudConfig = {
  key: 'cageWarehouseTransfers',
  title: 'aqua.pages.cageWarehouseTransfers.title',
  description: 'aqua.pages.cageWarehouseTransfers.description',
  endpoint: 'CageWarehouseTransfer',
  postingSlug: 'cage-warehouse-transfer',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferNo', label: 'aqua.fields.transferNo', type: 'text', required: true },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'transferNo', label: 'aqua.fields.transferNo' },
    { key: 'transferDate', label: 'aqua.fields.transferDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
  ],
  defaultValues: { status: 0 },
};

export const cageWarehouseTransferLinesConfig: AquaCrudConfig = {
  key: 'cageWarehouseTransferLines',
  title: 'aqua.pages.cageWarehouseTransferLines.title',
  description: 'aqua.pages.cageWarehouseTransferLines.description',
  endpoint: 'CageWarehouseTransferLine',
  createEndpoint: 'CageWarehouseTransferLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'cageWarehouseTransferId',
      label: 'aqua.fields.cageWarehouseTransferId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'CageWarehouseTransfer',
        labelKeys: ['transferNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromProjectCageId',
      label: 'aqua.fields.fromProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'toWarehouseId',
      label: 'aqua.fields.toWarehouseId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Warehouse',
        labelKeys: ['erpWarehouseCode', 'warehouseName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'fromProjectCode', label: 'aqua.fields.projectCode' },
    { key: 'fromCageCode', label: 'aqua.fields.fromCageCode' },
    { key: 'fromCageName', label: 'aqua.fields.cageName' },
    { key: 'toWarehouseCode', label: 'aqua.fields.toWarehouseCode' },
    { key: 'toWarehouseName', label: 'aqua.fields.toWarehouseId' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { transferDate: localDateString() },
};

export const warehouseCageTransfersConfig: AquaCrudConfig = {
  key: 'warehouseCageTransfers',
  title: 'aqua.pages.warehouseCageTransfers.title',
  description: 'aqua.pages.warehouseCageTransfers.description',
  endpoint: 'WarehouseCageTransfer',
  postingSlug: 'warehouse-cage-transfer',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferNo', label: 'aqua.fields.transferNo', type: 'text', required: true },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'transferNo', label: 'aqua.fields.transferNo' },
    { key: 'transferDate', label: 'aqua.fields.transferDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
  ],
  defaultValues: { status: 0 },
};

export const warehouseCageTransferLinesConfig: AquaCrudConfig = {
  key: 'warehouseCageTransferLines',
  title: 'aqua.pages.warehouseCageTransferLines.title',
  description: 'aqua.pages.warehouseCageTransferLines.description',
  endpoint: 'WarehouseCageTransferLine',
  createEndpoint: 'WarehouseCageTransferLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'warehouseCageTransferId',
      label: 'aqua.fields.warehouseCageTransferId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'WarehouseCageTransfer',
        labelKeys: ['transferNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromWarehouseId',
      label: 'aqua.fields.fromWarehouseId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Warehouse',
        labelKeys: ['erpWarehouseCode', 'warehouseName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    {
      key: 'toProjectCageId',
      label: 'aqua.fields.toProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'fromWarehouseCode', label: 'aqua.fields.fromWarehouseCode' },
    { key: 'fromWarehouseName', label: 'aqua.fields.fromWarehouseId' },
    { key: 'toProjectCode', label: 'aqua.fields.projectCode' },
    { key: 'toCageCode', label: 'aqua.fields.toCageCode' },
    { key: 'toCageName', label: 'aqua.fields.cageName' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { transferDate: localDateString() },
};
