import type { AquaCrudConfig } from '@/features/aqua-core/types/aqua-crud';
import { localDateString } from '@/features/quick-daily-entry/utils/quick-operations';

const currencyCodeOptions = [
  { label: 'TRY', value: 'TRY' },
  { label: 'USD', value: 'USD' },
  { label: 'EUR', value: 'EUR' },
  { label: 'GBP', value: 'GBP' },
];

export const shipmentsConfig: AquaCrudConfig = {
  key: 'shipments',
  title: 'aqua.pages.shipments.title',
  description: 'aqua.pages.shipments.description',
  endpoint: 'Shipment',
  postingSlug: 'shipment',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'shipmentNo', label: 'aqua.fields.shipmentNo', type: 'text', required: true },
    { key: 'shipmentDate', label: 'aqua.fields.shipmentDate', type: 'date', required: true },
    {
      key: 'targetWarehouseId',
      label: 'aqua.fields.warehouseName',
      type: 'select',
      lookup: {
        endpoint: 'Warehouse',
        labelKeys: ['erpWarehouseCode', 'warehouseName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'shipmentNo', label: 'aqua.fields.shipmentNo' },
    { key: 'shipmentDate', label: 'aqua.fields.shipmentDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'targetWarehouseCode', label: 'aqua.fields.warehouseCode' },
    { key: 'targetWarehouseName', label: 'aqua.fields.warehouseName' },
  ],
  defaultValues: { status: 0 },
};

export const shipmentLinesConfig: AquaCrudConfig = {
  key: 'shipmentLines',
  title: 'aqua.pages.shipmentLines.title',
  description: 'aqua.pages.shipmentLines.description',
  endpoint: 'ShipmentLine',
  createEndpoint: 'ShipmentLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'shipmentDate', label: 'aqua.fields.shipmentDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'shipmentId',
      label: 'aqua.fields.shipmentId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'Shipment',
        labelKeys: ['shipmentNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromProjectCageId',
      label: 'aqua.fields.fromProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'currencyCode', label: 'aqua.fields.currencyCode', type: 'select', options: currencyCodeOptions },
    { key: 'exchangeRate', label: 'aqua.fields.exchangeRate', type: 'number' },
    { key: 'unitPrice', label: 'aqua.fields.unitPrice', type: 'number' },
    { key: 'localUnitPrice', label: 'aqua.fields.localUnitPrice', type: 'number' },
    { key: 'lineAmount', label: 'aqua.fields.lineAmount', type: 'number' },
    { key: 'localLineAmount', label: 'aqua.fields.localLineAmount', type: 'number' },
  ],
  columns: [
    { key: 'shipmentNo', label: 'aqua.fields.shipmentId' },
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'fromCageCode', label: 'aqua.fields.fromCageCode' },
    { key: 'fromCageName', label: 'aqua.fields.cageName' },
    { key: 'targetWarehouseCode', label: 'aqua.fields.warehouseCode' },
    { key: 'targetWarehouseName', label: 'aqua.fields.warehouseName' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
    { key: 'currencyCode', label: 'aqua.fields.currencyCode' },
    { key: 'unitPrice', label: 'aqua.fields.unitPrice' },
    { key: 'localLineAmount', label: 'aqua.fields.localLineAmount' },
  ],
  defaultValues: { currencyCode: 'TRY', exchangeRate: 1, unitPrice: 0, shipmentDate: localDateString() },
};
