import type { AquaCrudConfig } from '@/features/aqua-core/types/aqua-crud';

const booleanOptions = [
  { label: 'common:yes', value: 'true' },
  { label: 'common:no', value: 'false' },
];

export const fishBatchesConfig: AquaCrudConfig = {
  key: 'fishBatches',
  title: 'aqua.pages.fishBatches.title',
  description: 'aqua.pages.fishBatches.description',
  endpoint: 'FishBatch',
  listStaleTimeMs: 30000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'batchCode', label: 'aqua.fields.batchCode', type: 'text', required: true },
    {
      key: 'fishStockId',
      label: 'aqua.fields.fishStockId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: '/api/Stock',
        labelKeys: ['erpStockCode', 'stockName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'currentAverageGram', label: 'aqua.fields.currentAverageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'startDate', label: 'aqua.fields.startDate', type: 'date', required: true },
    {
      key: 'sourceGoodsReceiptLineId',
      label: 'aqua.fields.sourceGoodsReceiptLineId',
      type: 'select',
      lookup: {
        endpoint: 'GoodsReceiptLine',
        labelKeys: ['stock.stockName', 'itemType', 'id'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'supplierId', label: 'aqua.fields.supplierId', type: 'number' },
    { key: 'supplierLotCode', label: 'aqua.fields.supplierLotCode', type: 'text' },
    { key: 'hatcheryName', label: 'aqua.fields.hatcheryName', type: 'text' },
    { key: 'originCountryCode', label: 'aqua.fields.originCountryCode', type: 'text' },
    { key: 'strainCode', label: 'aqua.fields.strainCode', type: 'text' },
    { key: 'generationCode', label: 'aqua.fields.generationCode', type: 'text' },
    { key: 'broodstockCode', label: 'aqua.fields.broodstockCode', type: 'text' },
    { key: 'isVaccinated', label: 'aqua.fields.isVaccinated', type: 'select', options: booleanOptions },
    { key: 'vaccinationDate', label: 'aqua.fields.vaccinationDate', type: 'date' },
    { key: 'vaccinationNote', label: 'aqua.fields.vaccinationNote', type: 'textarea' },
    { key: 'treatmentHistoryNote', label: 'aqua.fields.treatmentHistoryNote', type: 'textarea' },
    { key: 'targetHarvestAverageGram', label: 'aqua.fields.targetHarvestAverageGram', type: 'number', unitTransform: 'gram-to-kg' },
    { key: 'targetHarvestDate', label: 'aqua.fields.targetHarvestDate', type: 'date' },
    { key: 'targetHarvestClass', label: 'aqua.fields.targetHarvestClass', type: 'text' },
    { key: 'qualityGrade', label: 'aqua.fields.qualityGrade', type: 'text' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'fishStockCode', label: 'aqua.fields.stockCode' },
    { key: 'fishStockName', label: 'aqua.fields.stockName' },
    { key: 'currentAverageGram', label: 'aqua.fields.currentAverageGram', unitTransform: 'gram-to-kg' },
    { key: 'startDate', label: 'aqua.fields.startDate' },
    { key: 'supplierLotCode', label: 'aqua.fields.supplierLotCode' },
    { key: 'targetHarvestAverageGram', label: 'aqua.fields.targetHarvestAverageGram', unitTransform: 'gram-to-kg' },
    { key: 'targetHarvestDate', label: 'aqua.fields.targetHarvestDate' },
  ],
  defaultValues: { isVaccinated: false },
};
