export { ProjectsPage } from '@/features/projects';
export { CagesPage, CageWarehouseMappingsPage } from '@/features/cages';
export { ProjectCageAssignmentsPage } from '@/features/project-cages';
export { WeatherSeveritiesPage, WeatherTypesPage } from '@/features/weather';
export { SeaWaterTemperaturesPage } from '@/features/sea-water-temperature';
export { WindDirectionsPage } from '@/features/wind-direction';
export { CurrentDirectionsPage } from '@/features/current-direction';
export { NetOperationTypesPage, NetOperationsPage } from '@/features/net-operations';
export { AquaSettingsPage } from '@/features/aqua-settings';
export { QuickSetupPage } from '@/features/quick-setup';
export { QuickDailyEntryPage } from '@/features/quick-daily-entry';
export { OpeningImportPage } from '@/features/opening-import';
export { ProjectMergesPage } from '@/features/project-merges';
export { GoodsReceiptsPage } from '@/features/goods-receipts';
export { FeedingsPage } from '@/features/feedings';
export { MortalitiesPage } from '@/features/mortalities';
export { TransfersPage } from '@/features/transfers';
export { ShipmentsPage } from '@/features/shipments';
export { WeighingsPage } from '@/features/weighings';
export { StockConvertsPage } from '@/features/stock-converts';
export { FishBatchesPage } from '@/features/fish-batches';
export { DailyWeathersPage } from '@/features/daily-weathers';
export { BatchMovementsPage } from '@/features/batch-movements';
export { CageBalancesPage } from '@/features/cage-balances';
export { ProjectDetailReportPage } from '@/features/project-detail-report';
export { AquaDashboardPage } from '@/features/aqua-dashboard';
export { RawKpiReportPage } from '@/features/raw-kpi-report';
export { BusinessKpiReportPage } from '@/features/business-kpi-report';
export { DevirFcrReportPage } from '@/features/devir-fcr-report';
