export { goodsReceiptsConfig, goodsReceiptLinesConfig, goodsReceiptFishDistributionsConfig } from '@/features/goods-receipts/config/page-configs';
export { feedingsConfig, feedingLinesConfig, feedingDistributionsConfig } from '@/features/feedings/config/page-configs';
export { mortalitiesConfig, mortalityLinesConfig } from '@/features/mortalities/config/page-configs';
export { transfersConfig, transferLinesConfig, warehouseTransfersConfig, warehouseTransferLinesConfig, cageWarehouseTransfersConfig, cageWarehouseTransferLinesConfig, warehouseCageTransfersConfig, warehouseCageTransferLinesConfig } from '@/features/transfers/config/page-configs';
export { shipmentsConfig, shipmentLinesConfig } from '@/features/shipments/config/page-configs';
export { weighingsConfig, weighingLinesConfig } from '@/features/weighings/config/page-configs';
export { stockConvertsConfig, stockConvertLinesConfig } from '@/features/stock-converts/config/page-configs';
export { dailyWeathersConfig } from '@/features/daily-weathers/config/page-configs';
export { fishBatchesConfig } from '@/features/fish-batches/config/page-configs';
export { netOperationsConfig, netOperationLinesConfig } from '@/features/net-operations/config/page-configs';
