import type { AquaCrudConfig } from '@/features/aqua/shared/types/aqua-crud';
import { localDateString } from '../quick-daily-entry/utils/quick-operations';

const goodsReceiptItemTypeOptions = [
  { label: 'aqua.goodsReceiptItemType.feed', value: 0 },
  { label: 'aqua.goodsReceiptItemType.fish', value: 1 },
];

const currencyCodeOptions = [
  { label: 'TRY', value: 'TRY' },
  { label: 'USD', value: 'USD' },
  { label: 'EUR', value: 'EUR' },
  { label: 'GBP', value: 'GBP' },
];

const booleanOptions = [
  { label: 'common:yes', value: 'true' },
  { label: 'common:no', value: 'false' },
];

export const goodsReceiptsConfig: AquaCrudConfig = {
  key: 'goodsReceipts',
  title: 'aqua.pages.goodsReceipts.title',
  description: 'aqua.pages.goodsReceipts.description',
  endpoint: 'GoodsReceipt',
  postingSlug: 'goods-receipt',
  autoPostOnSave: true,
  listStaleTimeMs: 15000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'receiptNo', label: 'aqua.fields.receiptNo', type: 'text', required: true },
    { key: 'receiptDate', label: 'aqua.fields.receiptDate', type: 'date', required: true },
    { key: 'supplierId', label: 'aqua.fields.supplierId', type: 'number' },
    {
      key: 'warehouseId',
      label: 'aqua.fields.warehouseName',
      type: 'select',
      lookup: {
        endpoint: 'Warehouse',
        labelKeys: ['erpWarehouseCode', 'warehouseName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'receiptNo', label: 'aqua.fields.receiptNo' },
    { key: 'receiptDate', label: 'aqua.fields.receiptDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'warehouseCode', label: 'aqua.fields.warehouseCode' },
    { key: 'warehouseName', label: 'aqua.fields.warehouseName' },
  ],
  defaultValues: { status: 0 },
};

export const feedingsConfig: AquaCrudConfig = {
  key: 'feedings',
  title: 'aqua.pages.feedings.title',
  description: 'aqua.pages.feedings.description',
  endpoint: 'Feeding',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'feedingNo', label: 'aqua.fields.feedingNo', type: 'text', required: true },
    { key: 'feedingDate', label: 'aqua.fields.feedingDate', type: 'datetime', required: true },
    {
      key: 'feedingSlot',
      label: 'aqua.fields.feedingSlot',
      type: 'select',
      required: true,
      options: [
        { label: 'aqua.feedingSlot.morning', value: 0 },
        { label: 'aqua.feedingSlot.evening', value: 1 },
      ],
    },
    {
      key: 'sourceType',
      label: 'aqua.fields.sourceType',
      type: 'select',
      required: true,
      options: [
        { label: 'aqua.sourceType.manual', value: 0 },
        { label: 'aqua.sourceType.planned', value: 1 },
        { label: 'aqua.sourceType.auto', value: 2 },
      ],
    },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'feedingNo', label: 'aqua.fields.feedingNo' },
    { key: 'feedingDate', label: 'aqua.fields.feedingDate' },
    { key: 'feedingSlot', label: 'aqua.fields.feedingSlot' },
  ],
  defaultValues: { feedingSlot: 0, sourceType: 0 },
};

export const mortalitiesConfig: AquaCrudConfig = {
  key: 'mortalities',
  title: 'aqua.pages.mortalities.title',
  description: 'aqua.pages.mortalities.description',
  endpoint: 'Mortality',
  postingSlug: 'mortality',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'mortalityDate', label: 'aqua.fields.mortalityDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'mortalityDate', label: 'aqua.fields.mortalityDate' },
  ],
  defaultValues: { status: 0 },
};

export const transfersConfig: AquaCrudConfig = {
  key: 'transfers',
  title: 'aqua.pages.transfers.title',
  description: 'aqua.pages.transfers.description',
  endpoint: 'Transfer',
  postingSlug: 'transfer',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferNo', label: 'aqua.fields.transferNo', type: 'text', required: true },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'transferNo', label: 'aqua.fields.transferNo' },
    { key: 'transferDate', label: 'aqua.fields.transferDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
  ],
  defaultValues: { status: 0 },
};

export const shipmentsConfig: AquaCrudConfig = {
  key: 'shipments',
  title: 'aqua.pages.shipments.title',
  description: 'aqua.pages.shipments.description',
  endpoint: 'Shipment',
  postingSlug: 'shipment',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'shipmentNo', label: 'aqua.fields.shipmentNo', type: 'text', required: true },
    { key: 'shipmentDate', label: 'aqua.fields.shipmentDate', type: 'date', required: true },
    {
      key: 'targetWarehouseId',
      label: 'aqua.fields.warehouseName',
      type: 'select',
      lookup: {
        endpoint: 'Warehouse',
        labelKeys: ['erpWarehouseCode', 'warehouseName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'shipmentNo', label: 'aqua.fields.shipmentNo' },
    { key: 'shipmentDate', label: 'aqua.fields.shipmentDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'targetWarehouseCode', label: 'aqua.fields.warehouseCode' },
    { key: 'targetWarehouseName', label: 'aqua.fields.warehouseName' },
  ],
  defaultValues: { status: 0 },
};

export const warehouseTransfersConfig: AquaCrudConfig = {
  key: 'warehouseTransfers',
  title: 'aqua.pages.warehouseTransfers.title',
  description: 'aqua.pages.warehouseTransfers.description',
  endpoint: 'WarehouseTransfer',
  postingSlug: 'warehouse-transfer',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferNo', label: 'aqua.fields.transferNo', type: 'text', required: true },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'transferNo', label: 'aqua.fields.transferNo' },
    { key: 'transferDate', label: 'aqua.fields.transferDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
  ],
  defaultValues: { status: 0 },
};

export const cageWarehouseTransfersConfig: AquaCrudConfig = {
  key: 'cageWarehouseTransfers',
  title: 'aqua.pages.cageWarehouseTransfers.title',
  description: 'aqua.pages.cageWarehouseTransfers.description',
  endpoint: 'CageWarehouseTransfer',
  postingSlug: 'cage-warehouse-transfer',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferNo', label: 'aqua.fields.transferNo', type: 'text', required: true },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'transferNo', label: 'aqua.fields.transferNo' },
    { key: 'transferDate', label: 'aqua.fields.transferDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
  ],
  defaultValues: { status: 0 },
};

export const warehouseCageTransfersConfig: AquaCrudConfig = {
  key: 'warehouseCageTransfers',
  title: 'aqua.pages.warehouseCageTransfers.title',
  description: 'aqua.pages.warehouseCageTransfers.description',
  endpoint: 'WarehouseCageTransfer',
  postingSlug: 'warehouse-cage-transfer',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferNo', label: 'aqua.fields.transferNo', type: 'text', required: true },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'transferNo', label: 'aqua.fields.transferNo' },
    { key: 'transferDate', label: 'aqua.fields.transferDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
  ],
  defaultValues: { status: 0 },
};

export const weighingsConfig: AquaCrudConfig = {
  key: 'weighings',
  title: 'aqua.pages.weighings.title',
  description: 'aqua.pages.weighings.description',
  endpoint: 'Weighing',
  postingSlug: 'weighing',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'weighingNo', label: 'aqua.fields.weighingNo', type: 'text', required: true },
    { key: 'weighingDate', label: 'aqua.fields.weighingDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'weighingNo', label: 'aqua.fields.weighingNo' },
    { key: 'weighingDate', label: 'aqua.fields.weighingDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
  ],
  defaultValues: { status: 0 },
};

export const stockConvertsConfig: AquaCrudConfig = {
  key: 'stockConverts',
  title: 'aqua.pages.stockConverts.title',
  description: 'aqua.pages.stockConverts.description',
  endpoint: 'StockConvert',
  postingSlug: 'stock-convert',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'convertNo', label: 'aqua.fields.convertNo', type: 'text', required: true },
    { key: 'convertDate', label: 'aqua.fields.convertDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'convertNo', label: 'aqua.fields.convertNo' },
    { key: 'convertDate', label: 'aqua.fields.convertDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
  ],
  defaultValues: { status: 0 },
};

export const dailyWeathersConfig: AquaCrudConfig = {
  key: 'dailyWeathers',
  title: 'aqua.pages.dailyWeathers.title',
  description: 'aqua.pages.dailyWeathers.description',
  endpoint: 'DailyWeather',
  listStaleTimeMs: 30000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'weatherDate', label: 'aqua.fields.weatherDate', type: 'date', required: true },
    {
      key: 'weatherTypeId',
      label: 'aqua.fields.weatherTypeId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'WeatherType',
        labelKeys: ['code', 'name'],
        valueKey: 'id',
        staleTimeMs: 120000,
      },
    },
    {
      key: 'weatherSeverityId',
      label: 'aqua.fields.weatherSeverityId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'WeatherSeverity',
        labelKeys: ['code', 'name'],
        valueKey: 'id',
        staleTimeMs: 120000,
      },
    },
    { key: 'temperatureC', label: 'aqua.fields.temperatureC', type: 'number' },
    { key: 'windKnot', label: 'aqua.fields.windKnot', type: 'number' },
    { key: 'waterTemperatureSurfaceC', label: 'aqua.fields.waterTemperatureSurfaceC', type: 'number' },
    { key: 'waterTemperatureDepthC', label: 'aqua.fields.waterTemperatureDepthC', type: 'number' },
    { key: 'dissolvedOxygenMgL', label: 'aqua.fields.dissolvedOxygenMgL', type: 'number' },
    { key: 'salinityPpt', label: 'aqua.fields.salinityPpt', type: 'number' },
    { key: 'ph', label: 'aqua.fields.ph', type: 'number' },
    { key: 'currentSpeedKn', label: 'aqua.fields.currentSpeedKn', type: 'number' },
    { key: 'waveHeightM', label: 'aqua.fields.waveHeightM', type: 'number' },
    { key: 'turbidityNtu', label: 'aqua.fields.turbidityNtu', type: 'number' },
    { key: 'ammoniaMgL', label: 'aqua.fields.ammoniaMgL', type: 'number' },
    { key: 'nitriteMgL', label: 'aqua.fields.nitriteMgL', type: 'number' },
    { key: 'algalBloomIndex', label: 'aqua.fields.algalBloomIndex', type: 'number' },
    { key: 'sensorHealthScore', label: 'aqua.fields.sensorHealthScore', type: 'number' },
    { key: 'sensorRecordedAt', label: 'aqua.fields.sensorRecordedAt', type: 'datetime' },
    { key: 'dataSource', label: 'aqua.fields.dataSource', type: 'text' },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'weatherDate', label: 'aqua.fields.weatherDate' },
    { key: 'weatherTypeName', label: 'aqua.fields.weatherTypeId' },
    { key: 'weatherSeverityName', label: 'aqua.fields.weatherSeverityId' },
    { key: 'weatherSeverityScore', label: 'aqua.fields.weatherSeverityScore' },
    { key: 'operationalRiskScore', label: 'aqua.fields.operationalRiskScore' },
    { key: 'operationalRiskLevel', label: 'aqua.fields.operationalRiskLevel' },
    { key: 'dissolvedOxygenMgL', label: 'aqua.fields.dissolvedOxygenMgL' },
    { key: 'salinityPpt', label: 'aqua.fields.salinityPpt' },
    { key: 'ph', label: 'aqua.fields.ph' },
  ],
};

export const fishBatchesConfig: AquaCrudConfig = {
  key: 'fishBatches',
  title: 'aqua.pages.fishBatches.title',
  description: 'aqua.pages.fishBatches.description',
  endpoint: 'FishBatch',
  listStaleTimeMs: 30000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'batchCode', label: 'aqua.fields.batchCode', type: 'text', required: true },
    {
      key: 'fishStockId',
      label: 'aqua.fields.fishStockId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: '/api/Stock',
        labelKeys: ['erpStockCode', 'stockName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'currentAverageGram', label: 'aqua.fields.currentAverageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'startDate', label: 'aqua.fields.startDate', type: 'date', required: true },
    {
      key: 'sourceGoodsReceiptLineId',
      label: 'aqua.fields.sourceGoodsReceiptLineId',
      type: 'select',
      lookup: {
        endpoint: 'GoodsReceiptLine',
        labelKeys: ['stock.stockName', 'itemType', 'id'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'supplierId', label: 'aqua.fields.supplierId', type: 'number' },
    { key: 'supplierLotCode', label: 'aqua.fields.supplierLotCode', type: 'text' },
    { key: 'hatcheryName', label: 'aqua.fields.hatcheryName', type: 'text' },
    { key: 'originCountryCode', label: 'aqua.fields.originCountryCode', type: 'text' },
    { key: 'strainCode', label: 'aqua.fields.strainCode', type: 'text' },
    { key: 'generationCode', label: 'aqua.fields.generationCode', type: 'text' },
    { key: 'broodstockCode', label: 'aqua.fields.broodstockCode', type: 'text' },
    { key: 'isVaccinated', label: 'aqua.fields.isVaccinated', type: 'select', options: booleanOptions },
    { key: 'vaccinationDate', label: 'aqua.fields.vaccinationDate', type: 'date' },
    { key: 'vaccinationNote', label: 'aqua.fields.vaccinationNote', type: 'textarea' },
    { key: 'treatmentHistoryNote', label: 'aqua.fields.treatmentHistoryNote', type: 'textarea' },
    { key: 'targetHarvestAverageGram', label: 'aqua.fields.targetHarvestAverageGram', type: 'number', unitTransform: 'gram-to-kg' },
    { key: 'targetHarvestDate', label: 'aqua.fields.targetHarvestDate', type: 'date' },
    { key: 'targetHarvestClass', label: 'aqua.fields.targetHarvestClass', type: 'text' },
    { key: 'qualityGrade', label: 'aqua.fields.qualityGrade', type: 'text' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'fishStockCode', label: 'aqua.fields.stockCode' },
    { key: 'fishStockName', label: 'aqua.fields.stockName' },
    { key: 'currentAverageGram', label: 'aqua.fields.currentAverageGram', unitTransform: 'gram-to-kg' },
    { key: 'startDate', label: 'aqua.fields.startDate' },
    { key: 'supplierLotCode', label: 'aqua.fields.supplierLotCode' },
    { key: 'targetHarvestAverageGram', label: 'aqua.fields.targetHarvestAverageGram', unitTransform: 'gram-to-kg' },
    { key: 'targetHarvestDate', label: 'aqua.fields.targetHarvestDate' },
  ],
  defaultValues: { isVaccinated: false },
};

export const netOperationsConfig: AquaCrudConfig = {
  key: 'netOperations',
  title: 'aqua.pages.netOperations.title',
  description: 'aqua.pages.netOperations.description',
  endpoint: 'NetOperation',
  postingSlug: 'net-operation',
  autoPostOnSave: true,
  listStaleTimeMs: 15000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    {
      key: 'operationTypeId',
      label: 'aqua.fields.operationTypeId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'NetOperationType',
        labelKey: 'name',
        valueKey: 'id',
        staleTimeMs: 120000,
      },
    },
    { key: 'operationNo', label: 'aqua.fields.operationNo', type: 'text', required: true },
    { key: 'operationDate', label: 'aqua.fields.operationDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'operationNo', label: 'aqua.fields.operationNo' },
    { key: 'operationDate', label: 'aqua.fields.operationDate' },
    { key: 'operationTypeName', label: 'aqua.fields.operationTypeId' },
  ],
  defaultValues: { status: 0 },
};

export const goodsReceiptLinesConfig: AquaCrudConfig = {
  key: 'goodsReceiptLines',
  title: 'aqua.pages.goodsReceiptLines.title',
  description: 'aqua.pages.goodsReceiptLines.description',
  endpoint: 'GoodsReceiptLine',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'goodsReceiptId',
      label: 'aqua.fields.goodsReceiptId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'GoodsReceipt',
        labelKeys: ['receiptNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'itemType', label: 'aqua.fields.itemType', type: 'select', required: true, options: goodsReceiptItemTypeOptions },
    {
      key: 'stockId',
      label: 'aqua.fields.stockName',
      type: 'select',
      required: true,
      lookup: {
        endpoint: '/api/Stock',
        labelKeys: ['erpStockCode', 'stockName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'qtyUnit', label: 'aqua.fields.qtyUnit', type: 'number', visibleWhen: { fieldKey: 'itemType', values: [0] } },
    { key: 'gramPerUnit', label: 'aqua.fields.gramPerUnit', type: 'number', unitTransform: 'gram-to-kg', visibleWhen: { fieldKey: 'itemType', values: [0] } },
    { key: 'totalGram', label: 'aqua.fields.totalGram', type: 'number', unitTransform: 'gram-to-kg', visibleWhen: { fieldKey: 'itemType', values: [0] } },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', visibleWhen: { fieldKey: 'itemType', values: [1] } },
    { key: 'fishAverageGram', label: 'aqua.fields.fishAverageGram', type: 'number', unitTransform: 'gram-to-kg', visibleWhen: { fieldKey: 'itemType', values: [1] } },
    { key: 'fishTotalGram', label: 'aqua.fields.fishTotalGram', type: 'number', unitTransform: 'gram-to-kg', visibleWhen: { fieldKey: 'itemType', values: [1] } },
    { key: 'currencyCode', label: 'aqua.fields.currencyCode', type: 'select', options: currencyCodeOptions },
    { key: 'exchangeRate', label: 'aqua.fields.exchangeRate', type: 'number' },
    { key: 'unitPrice', label: 'aqua.fields.unitPrice', type: 'number' },
    { key: 'localUnitPrice', label: 'aqua.fields.localUnitPrice', type: 'number' },
    { key: 'lineAmount', label: 'aqua.fields.lineAmount', type: 'number' },
    { key: 'localLineAmount', label: 'aqua.fields.localLineAmount', type: 'number' },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      visibleWhen: { fieldKey: 'itemType', values: [1] },
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
  ],
  columns: [
    { key: 'itemType', label: 'aqua.fields.itemType' },
    { key: 'stock.erpStockCode', label: 'aqua.fields.stockCode' },
    { key: 'stock.stockName', label: 'aqua.fields.stockName' },
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'totalGram', label: 'aqua.fields.totalGram', unitTransform: 'gram-to-kg' },
    { key: 'fishTotalGram', label: 'aqua.fields.fishTotalGram', unitTransform: 'gram-to-kg' },
    { key: 'currencyCode', label: 'aqua.fields.currencyCode' },
    { key: 'unitPrice', label: 'aqua.fields.unitPrice' },
    { key: 'localLineAmount', label: 'aqua.fields.localLineAmount' },
  ],
  defaultValues: { currencyCode: 'TRY', exchangeRate: 1 },
};

export const goodsReceiptFishDistributionsConfig: AquaCrudConfig = {
  key: 'goodsReceiptFishDistributions',
  title: 'aqua.pages.goodsReceiptFishDistributions.title',
  description: 'aqua.pages.goodsReceiptFishDistributions.description',
  endpoint: 'GoodsReceiptFishDistribution',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'goodsReceiptLineId',
      label: 'aqua.fields.goodsReceiptLineId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'GoodsReceiptLine',
        labelKeys: ['stock.stockName', 'itemType', 'id'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'projectCageId',
      label: 'aqua.fields.projectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
  ],
  columns: [
    { key: 'stockCode', label: 'aqua.fields.stockCode' },
    { key: 'stockName', label: 'aqua.fields.stockName' },
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'cageCode', label: 'aqua.fields.cageCode' },
    { key: 'cageName', label: 'aqua.fields.cageName' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
  ],
};

export const feedingLinesConfig: AquaCrudConfig = {
  key: 'feedingLines',
  title: 'aqua.pages.feedingLines.title',
  description: 'aqua.pages.feedingLines.description',
  endpoint: 'FeedingLine',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'feedingId',
      label: 'aqua.fields.feedingId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Feeding',
        labelKeys: ['feedingNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'stockId',
      label: 'aqua.fields.stockName',
      type: 'select',
      required: true,
      lookup: {
        endpoint: '/api/Stock',
        labelKeys: ['erpStockCode', 'stockName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'qtyUnit', label: 'aqua.fields.qtyUnit', type: 'number', required: true },
    { key: 'gramPerUnit', label: 'aqua.fields.gramPerUnit', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'totalGram', label: 'aqua.fields.totalGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'stockCode', label: 'aqua.fields.stockCode' },
    { key: 'stockName', label: 'aqua.fields.stockName' },
    { key: 'qtyUnit', label: 'aqua.fields.qtyUnit' },
    { key: 'gramPerUnit', label: 'aqua.fields.gramPerUnit', unitTransform: 'gram-to-kg' },
    { key: 'totalGram', label: 'aqua.fields.totalGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { gramPerUnit: 1 },
};

export const feedingDistributionsConfig: AquaCrudConfig = {
  key: 'feedingDistributions',
  title: 'aqua.pages.feedingDistributions.title',
  description: 'aqua.pages.feedingDistributions.description',
  endpoint: 'FeedingDistribution',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'feedingLineId',
      label: 'aqua.fields.feedingLineId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FeedingLine',
        labelKeys: ['stock.stockName', 'totalGram', 'id'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'projectCageId',
      label: 'aqua.fields.projectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    { key: 'feedGram', label: 'aqua.fields.feedGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'cageCode', label: 'aqua.fields.cageCode' },
    { key: 'cageName', label: 'aqua.fields.cageName' },
    { key: 'feedGram', label: 'aqua.fields.feedGram', unitTransform: 'gram-to-kg' },
  ],
};

export const transferLinesConfig: AquaCrudConfig = {
  key: 'transferLines',
  title: 'aqua.pages.transferLines.title',
  description: 'aqua.pages.transferLines.description',
  endpoint: 'TransferLine',
  createEndpoint: 'TransferLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'transferId',
      label: 'aqua.fields.transferId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'Transfer',
        labelKeys: ['transferNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromProjectCageId',
      label: 'aqua.fields.fromProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'toProjectCageId',
      label: 'aqua.fields.toProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'fromProjectCode', label: 'aqua.fields.projectCode' },
    { key: 'fromCageCode', label: 'aqua.fields.fromCageCode' },
    { key: 'fromCageName', label: 'aqua.fields.cageName' },
    { key: 'toProjectCode', label: 'aqua.fields.projectCode' },
    { key: 'toCageCode', label: 'aqua.fields.toCageCode' },
    { key: 'toCageName', label: 'aqua.fields.cageName' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { transferDate: localDateString() },
};

export const warehouseTransferLinesConfig: AquaCrudConfig = {
  key: 'warehouseTransferLines',
  title: 'aqua.pages.warehouseTransferLines.title',
  description: 'aqua.pages.warehouseTransferLines.description',
  endpoint: 'WarehouseTransferLine',
  createEndpoint: 'WarehouseTransferLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'warehouseTransferId',
      label: 'aqua.fields.warehouseTransferId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'WarehouseTransfer',
        labelKeys: ['transferNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromWarehouseId',
      label: 'aqua.fields.fromWarehouseId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Warehouse',
        labelKeys: ['erpWarehouseCode', 'warehouseName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    {
      key: 'toWarehouseId',
      label: 'aqua.fields.toWarehouseId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Warehouse',
        labelKeys: ['erpWarehouseCode', 'warehouseName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'fromWarehouseCode', label: 'aqua.fields.fromWarehouseCode' },
    { key: 'fromWarehouseName', label: 'aqua.fields.fromWarehouseId' },
    { key: 'toWarehouseCode', label: 'aqua.fields.toWarehouseCode' },
    { key: 'toWarehouseName', label: 'aqua.fields.toWarehouseId' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { transferDate: localDateString() },
};

export const cageWarehouseTransferLinesConfig: AquaCrudConfig = {
  key: 'cageWarehouseTransferLines',
  title: 'aqua.pages.cageWarehouseTransferLines.title',
  description: 'aqua.pages.cageWarehouseTransferLines.description',
  endpoint: 'CageWarehouseTransferLine',
  createEndpoint: 'CageWarehouseTransferLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'cageWarehouseTransferId',
      label: 'aqua.fields.cageWarehouseTransferId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'CageWarehouseTransfer',
        labelKeys: ['transferNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromProjectCageId',
      label: 'aqua.fields.fromProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'toWarehouseId',
      label: 'aqua.fields.toWarehouseId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Warehouse',
        labelKeys: ['erpWarehouseCode', 'warehouseName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'fromProjectCode', label: 'aqua.fields.projectCode' },
    { key: 'fromCageCode', label: 'aqua.fields.fromCageCode' },
    { key: 'fromCageName', label: 'aqua.fields.cageName' },
    { key: 'toWarehouseCode', label: 'aqua.fields.toWarehouseCode' },
    { key: 'toWarehouseName', label: 'aqua.fields.toWarehouseId' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { transferDate: localDateString() },
};

export const warehouseCageTransferLinesConfig: AquaCrudConfig = {
  key: 'warehouseCageTransferLines',
  title: 'aqua.pages.warehouseCageTransferLines.title',
  description: 'aqua.pages.warehouseCageTransferLines.description',
  endpoint: 'WarehouseCageTransferLine',
  createEndpoint: 'WarehouseCageTransferLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'transferDate', label: 'aqua.fields.transferDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'warehouseCageTransferId',
      label: 'aqua.fields.warehouseCageTransferId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'WarehouseCageTransfer',
        labelKeys: ['transferNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromWarehouseId',
      label: 'aqua.fields.fromWarehouseId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Warehouse',
        labelKeys: ['erpWarehouseCode', 'warehouseName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    {
      key: 'toProjectCageId',
      label: 'aqua.fields.toProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'fromWarehouseCode', label: 'aqua.fields.fromWarehouseCode' },
    { key: 'fromWarehouseName', label: 'aqua.fields.fromWarehouseId' },
    { key: 'toProjectCode', label: 'aqua.fields.projectCode' },
    { key: 'toCageCode', label: 'aqua.fields.toCageCode' },
    { key: 'toCageName', label: 'aqua.fields.cageName' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { transferDate: localDateString() },
};

export const shipmentLinesConfig: AquaCrudConfig = {
  key: 'shipmentLines',
  title: 'aqua.pages.shipmentLines.title',
  description: 'aqua.pages.shipmentLines.description',
  endpoint: 'ShipmentLine',
  createEndpoint: 'ShipmentLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'shipmentDate', label: 'aqua.fields.shipmentDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'shipmentId',
      label: 'aqua.fields.shipmentId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'Shipment',
        labelKeys: ['shipmentNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromProjectCageId',
      label: 'aqua.fields.fromProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'currencyCode', label: 'aqua.fields.currencyCode', type: 'select', options: currencyCodeOptions },
    { key: 'exchangeRate', label: 'aqua.fields.exchangeRate', type: 'number' },
    { key: 'unitPrice', label: 'aqua.fields.unitPrice', type: 'number' },
    { key: 'localUnitPrice', label: 'aqua.fields.localUnitPrice', type: 'number' },
    { key: 'lineAmount', label: 'aqua.fields.lineAmount', type: 'number' },
    { key: 'localLineAmount', label: 'aqua.fields.localLineAmount', type: 'number' },
  ],
  columns: [
    { key: 'shipmentNo', label: 'aqua.fields.shipmentId' },
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
    { key: 'fromCageCode', label: 'aqua.fields.fromCageCode' },
    { key: 'fromCageName', label: 'aqua.fields.cageName' },
    { key: 'targetWarehouseCode', label: 'aqua.fields.warehouseCode' },
    { key: 'targetWarehouseName', label: 'aqua.fields.warehouseName' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
    { key: 'currencyCode', label: 'aqua.fields.currencyCode' },
    { key: 'unitPrice', label: 'aqua.fields.unitPrice' },
    { key: 'localLineAmount', label: 'aqua.fields.localLineAmount' },
  ],
  defaultValues: { currencyCode: 'TRY', exchangeRate: 1, unitPrice: 0, shipmentDate: localDateString() },
};

export const mortalityLinesConfig: AquaCrudConfig = {
  key: 'mortalityLines',
  title: 'aqua.pages.mortalityLines.title',
  description: 'aqua.pages.mortalityLines.description',
  endpoint: 'MortalityLine',
  createEndpoint: 'MortalityLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'mortalityDate', label: 'aqua.fields.mortalityDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'mortalityId',
      label: 'aqua.fields.mortalityId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'Mortality',
        labelKeys: ['projectCode', 'mortalityDate'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'projectCageId',
      label: 'aqua.fields.projectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    { key: 'deadCount', label: 'aqua.fields.deadCount', type: 'number', required: true },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'cageCode', label: 'aqua.fields.cageCode' },
    { key: 'cageName', label: 'aqua.fields.cageName' },
    { key: 'deadCount', label: 'aqua.fields.deadCount' },
  ],
  defaultValues: { mortalityDate: localDateString() },
};

export const weighingLinesConfig: AquaCrudConfig = {
  key: 'weighingLines',
  title: 'aqua.pages.weighingLines.title',
  description: 'aqua.pages.weighingLines.description',
  endpoint: 'WeighingLine',
  createEndpoint: 'WeighingLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'weighingDate', label: 'aqua.fields.weighingDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'weighingId',
      label: 'aqua.fields.weighingId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'Weighing',
        labelKeys: ['weighingNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'projectCageId',
      label: 'aqua.fields.projectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    { key: 'measuredCount', label: 'aqua.fields.measuredCount', type: 'number', required: true },
    { key: 'measuredAverageGram', label: 'aqua.fields.measuredAverageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'measuredBiomassGram', label: 'aqua.fields.measuredBiomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'cageCode', label: 'aqua.fields.cageCode' },
    { key: 'cageName', label: 'aqua.fields.cageName' },
    { key: 'measuredCount', label: 'aqua.fields.measuredCount' },
    { key: 'measuredAverageGram', label: 'aqua.fields.measuredAverageGram', unitTransform: 'gram-to-kg' },
    { key: 'measuredBiomassGram', label: 'aqua.fields.measuredBiomassGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { weighingDate: localDateString() },
};

export const stockConvertLinesConfig: AquaCrudConfig = {
  key: 'stockConvertLines',
  title: 'aqua.pages.stockConvertLines.title',
  description: 'aqua.pages.stockConvertLines.description',
  endpoint: 'StockConvertLine',
  createEndpoint: 'StockConvertLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'convertDate', label: 'aqua.fields.convertDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'stockConvertId',
      label: 'aqua.fields.stockConvertId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'StockConvert',
        labelKeys: ['convertNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fromFishBatchId',
      label: 'aqua.fields.fromFishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'toFishBatchId',
      label: 'aqua.fields.toFishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromProjectCageId',
      label: 'aqua.fields.fromProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'toProjectCageId',
      label: 'aqua.fields.toProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'fromBatchCode', label: 'aqua.fields.fromFishBatchId' },
    { key: 'toBatchCode', label: 'aqua.fields.toFishBatchId' },
    { key: 'fromProjectCode', label: 'aqua.fields.projectCode' },
    { key: 'fromCageCode', label: 'aqua.fields.fromCageCode' },
    { key: 'fromCageName', label: 'aqua.fields.cageName' },
    { key: 'toCageCode', label: 'aqua.fields.toCageCode' },
    { key: 'toCageName', label: 'aqua.fields.cageName' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'newAverageGram', label: 'aqua.fields.newAverageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { convertDate: localDateString() },
};

export const netOperationLinesConfig: AquaCrudConfig = {
  key: 'netOperationLines',
  title: 'aqua.pages.netOperationLines.title',
  description: 'aqua.pages.netOperationLines.description',
  endpoint: 'NetOperationLine',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'netOperationId',
      label: 'aqua.fields.netOperationId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'NetOperation',
        labelKeys: ['operationNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'projectCageId',
      label: 'aqua.fields.projectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fishBatchId',
      label: 'aqua.fields.fishBatchId',
      type: 'select',
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'batchCode', label: 'aqua.fields.batchCode' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'cageCode', label: 'aqua.fields.cageCode' },
    { key: 'cageName', label: 'aqua.fields.cageName' },
    { key: 'note', label: 'aqua.fields.note' },
  ],
};
