import type { AquaCrudConfig } from '@/features/aqua-core/types/aqua-crud';
import { localDateString } from '@/features/quick-daily-entry/utils/quick-operations';

export const stockConvertsConfig: AquaCrudConfig = {
  key: 'stockConverts',
  title: 'aqua.pages.stockConverts.title',
  description: 'aqua.pages.stockConverts.description',
  endpoint: 'StockConvert',
  postingSlug: 'stock-convert',
  autoPostOnSave: true,
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'convertNo', label: 'aqua.fields.convertNo', type: 'text', required: true },
    { key: 'convertDate', label: 'aqua.fields.convertDate', type: 'date', required: true },
    { key: 'note', label: 'aqua.fields.note', type: 'textarea' },
  ],
  columns: [
    { key: 'convertNo', label: 'aqua.fields.convertNo' },
    { key: 'convertDate', label: 'aqua.fields.convertDate' },
    { key: 'projectCode', label: 'aqua.fields.projectCode' },
    { key: 'projectName', label: 'aqua.fields.projectName' },
  ],
  defaultValues: { status: 0 },
};

export const stockConvertLinesConfig: AquaCrudConfig = {
  key: 'stockConvertLines',
  title: 'aqua.pages.stockConvertLines.title',
  description: 'aqua.pages.stockConvertLines.description',
  endpoint: 'StockConvertLine',
  createEndpoint: 'StockConvertLine/auto-header',
  listStaleTimeMs: 10000,
  fields: [
    {
      key: 'projectId',
      label: 'aqua.fields.projectId',
      type: 'select',
      required: true,
      hideOnEdit: true,
      lookup: {
        endpoint: 'Project',
        labelKeys: ['projectCode', 'projectName'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 60000,
      },
    },
    { key: 'convertDate', label: 'aqua.fields.convertDate', type: 'date', required: true, hideOnEdit: true },
    {
      key: 'stockConvertId',
      label: 'aqua.fields.stockConvertId',
      type: 'select',
      required: true,
      hideInForm: true,
      lookup: {
        endpoint: 'StockConvert',
        labelKeys: ['convertNo'],
        valueKey: 'id',
        staleTimeMs: 30000,
      },
    },
    {
      key: 'fromFishBatchId',
      label: 'aqua.fields.fromFishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'toFishBatchId',
      label: 'aqua.fields.toFishBatchId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'FishBatch',
        labelKeys: ['batchCode'],
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'fromProjectCageId',
      label: 'aqua.fields.fromProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    {
      key: 'toProjectCageId',
      label: 'aqua.fields.toProjectCageId',
      type: 'select',
      required: true,
      lookup: {
        endpoint: 'ProjectCage',
        labelKeys: ['projectCode', 'cageCode'],
        labelSeparator: ' - ',
        valueKey: 'id',
        staleTimeMs: 30000,
        contextFilters: [{ sourceKey: 'projectId', column: 'ProjectId' }],
      },
    },
    { key: 'fishCount', label: 'aqua.fields.fishCount', type: 'number', required: true },
    { key: 'averageGram', label: 'aqua.fields.averageGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', type: 'number', required: true, unitTransform: 'gram-to-kg' },
  ],
  columns: [
    { key: 'fromBatchCode', label: 'aqua.fields.fromFishBatchId' },
    { key: 'toBatchCode', label: 'aqua.fields.toFishBatchId' },
    { key: 'fromProjectCode', label: 'aqua.fields.projectCode' },
    { key: 'fromCageCode', label: 'aqua.fields.fromCageCode' },
    { key: 'fromCageName', label: 'aqua.fields.cageName' },
    { key: 'toCageCode', label: 'aqua.fields.toCageCode' },
    { key: 'toCageName', label: 'aqua.fields.cageName' },
    { key: 'fishCount', label: 'aqua.fields.fishCount' },
    { key: 'averageGram', label: 'aqua.fields.averageGram', unitTransform: 'gram-to-kg' },
    { key: 'newAverageGram', label: 'aqua.fields.newAverageGram', unitTransform: 'gram-to-kg' },
    { key: 'biomassGram', label: 'aqua.fields.biomassGram', unitTransform: 'gram-to-kg' },
  ],
  defaultValues: { convertDate: localDateString() },
};
